jobs:
- job: ${{parameters.name}}
  pool: # Only 16.04 supports running containers. Thanks Microsoft.
    vmimage: ubuntu-16.04
  container:
    image: ${{parameters.container}}
    options: --entrypoint "/bin/sh -c 'apt-get install sudo -y'"
  steps:
  - task: Bash@3
    displayName: 'Run scripts/machine-setup.sh'
    inputs:
      targetType: filePath
      filePath: ./scripts/machine-setup.sh
  - task: Bash@3
    displayName: 'Run scripts/cibuild.sh'
    inputs:
      targetType: filePath
      filePath: ./scripts/cibuild.sh
      arguments: '--configuration ${{parameters.configuration}}'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: artifacts/build/${{parameters.configuration}}/tests/test_detail.xml
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: '${{parameters.name}}'
      buildConfiguration: ${{parameters.configuration}}
      buildPlatform: ${{parameters.architecture}}
